spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: proxy
          uri: http://localhost:8089
          predicates:
            - Path=/api/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: DEBUG
#    org.springframework.web.reactive: DEBUG
#    reactor.ipc.netty: DEBUG
#    reactor.netty: DEBUG
