spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: article
          uri: http://localhost:8083
          predicates:
            - Path=/api/articles
        - id: article
          uri: http://localhost:8083
          predicates:
            - Path=/api/articles/*
        - id: article
          uri: http://localhost:8083
          predicates:
            - Path=/api/articles/*/id
        - id: proxy
          uri: http://localhost:8089
          predicates:
            - Path=/api/articles/*/favorite
#        - id: proxy
#          uri: http://localhost:8089
#          predicates:
#            - Path=/api/articles/*/favorite-info
#        - id: proxy
#          uri: http://localhost:8089
#          predicates:
#            - Path=/api/favorite/*/article-ids
        - id: proxy
          uri: http://localhost:8089
          predicates:
            - Path=/api/articles/*/comments
        - id: proxy
          uri: http://localhost:8089
          predicates:
            - Path=/api/articles/*/comments/**
        - id: proxy
          uri: http://localhost:8089
          predicates:
           - Path=/api/tags/**
        - id: proxy
          uri: http://localhost:8089
          predicates:
            - Path=/api/profiles/**
        - id: proxy
          uri: http://localhost:8089
          predicates:
            - Path=/api/follow/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: DEBUG
#    org.springframework.web.reactive: DEBUG
#    reactor.ipc.netty: DEBUG
#    reactor.netty: DEBUG
