spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/api/profiles/*
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/api/profiles/by-id/*
        - id: follow
          uri: http://localhost:8082
          predicates:
            - Path=/api/profiles/*/follow
        - id: follow
          uri: http://localhost:8082
          predicates:
            - Path=/api/follow/**
        - id: article
          uri: http://localhost:8083
          predicates:
            - Path=/api/articles
        - id: article
          uri: http://localhost:8083
          predicates:
            - Path=/api/articles/*
        - id: article
          uri: http://localhost:8083
          predicates:
            - Path=/api/articles/*/id
        - id: tag
          uri: http://localhost:8084
          predicates:
            - Path=/api/articles/*/tags/list
        - id: tag
          uri: http://localhost:8084
          predicates:
            - Path=/api/articles/*/tags
        - id: tag
          uri: http://localhost:8084
          predicates:
            - Path=/api/tags
        - id: tag
          uri: http://localhost:8084
          predicates:
            - Path=/api/tags/**
        - id: favorite
          uri: http://localhost:8085
          predicates:
            - Path=/api/articles/*/favorite
        - id: favorite
          uri: http://localhost:8085
          predicates:
            - Path=/api/articles/*/favorite-info
        - id: favorite
          uri: http://localhost:8085
          predicates:
            - Path=/api/favorite/*/article-ids
        - id: comment
          uri: http://localhost:8086
          predicates:
            - Path=/api/articles/*/comments
        - id: comment
          uri: http://localhost:8086
          predicates:
            - Path=/api/articles/*/comments/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: DEBUG
#    org.springframework.web.reactive: DEBUG
#    reactor.ipc.netty: DEBUG
#    reactor.netty: DEBUG
