grpc:
  client:
    test:
      negotiation-type: plaintext
      address: 'static://127.0.0.1:9097'

  server:
    port: 9095

spring:
  application:
    name: favorite

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/rw-msa-favorite;AUTO_SERVER=TRUE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: on
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

