server:
  port: 8081

grpc:
  client:
    follow-grpc:
      negotiation-type: plaintext
      address: 'static://localhost:9092'

  server:
    port: 9091

spring:
  application:
    name: user

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/rw-msa-user;AUTO_SERVER=TRUE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: on
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

jwt:
  header: Authorization
  token-title: "Token "
  secret: 231qwefopjvkjksflj2iocksdmv89iwseknr23fsd89ihrn23jhv98iuoxrj2389jhcisdkrjh2398
  expiration-ms: 600_000_000 # 10 min
