server:
  port: 8083

grpc:
  client:
    profile-grpc:
      negotiation-type: plaintext
      address: 'static://localhost:9091'
    follow-grpc:
      negotiation-type: plaintext
      address: 'static://localhost:9092'
    tag-grpc:
      negotiation-type: plaintext
      address: 'static://localhost:9094'
    favorite-grpc:
      negotiation-type: plaintext
      address: 'static://localhost:9095'

  server:
    port: 9093

spring:
  application:
    name: article

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/rw-msa-article;AUTO_SERVER=TRUE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: on
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

jwt:
  header: Authorization
  token-title: "Token "
  secret: 231qwefopjvkjksflj2iocksdmv89iwseknr23fsd89ihrn23jhv98iuoxrj2389jhcisdkrjh2398
  expiration-ms: 600_000_000 # 10 min

logging:
  level:
    com.lodny.realworldmsaarticle.mapper: DEBUG


